backend:
  name: git-gateway
  branch: develop

local_backend: true

media_folder: static/media
public_folder: /media

collections:
  # Site
  - name: site
    label: "Site"
    editor:
      preview: false
    files:

      # Settings
      - name: settings
        label: "Settings"
        file: data/site/settings.yml
        fields:
          - { label: Logo, name: logo, widget: image }
          - { label: Background, name: background, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: string }
          - { label: "Footer Text", name: footer, widget: string }
      
      # Menu
      - file: data/site/menu.yml
        name: menu
        label: Menu
        fields:
          - name: menuLinks
            label: "Menu"
            widget: list
            types:
              - label: "Internal Page"
                name: internal
                widget: object
                summary: "{{fields.title}} (Internal Page Link)"
                fields:
                - { label: Title, name: title, widget: string }
                - label: Page
                  name: link
                  widget: select
                  options:
                    - { label: "Landing Page", value: "" }
                    - { label: "News", value: "news" }
                    - { label: "Music", value: "music" }
                    - { label: "Live", value: "live" }
                    - { label: "Contact", value: "contact" }
                - {label: ID, name: id, widget: ncw-id, prefix: menu, hidden: true}
              - label: "Custom Page"
                name: custom
                widget: object
                summary: "{{fields.title}} (Custom Page Link)"
                fields:
                - { label: Title, name: title, widget: string }
                - label: Page
                  name: link
                  widget: relation
                  collection: customPages
                  valueField: "page/{{slug}}"
                  searchFields: [title]
                  displayFields: [title]
                - {label: ID, name: id, widget: ncw-id, prefix: menu, hidden: true}
              - label: "External Link"
                name: external
                widget: object
                summary: "{{fields.title}} (External Link)"
                fields:
                - { label: Title, name: title, widget: string }
                - { label: URL, name: link, widget: string }
                - { label: ID, name: id, widget: ncw-id, prefix: menu, hidden: true }

      # Social Media
      - file: data/site/social.yml
        name: socialMedia
        label: "Social Media"
        fields:
          - name: socialMediaLinks
            label: "Social Media"   
            widget: list
            fields:
              - label: Title
                name: title
                widget: select
                options: [Facebook, LinkedIn, Instagram, iTunes, 'Apple Music', Snapchat, Soundcloud, Spotify, Twitter, YouTube]
              - {label: Link, name: link, widget: string}
              - {label: ID, name: id, widget: ncw-id, prefix: social, hidden: true}

      # Partners
      - file: data/site/partners.yml
        name: partners
        label: Partners
        fields:
          - name: partnerLinks
            label: "Partner Links"
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: ID, name: id, widget: ncw-id, prefix: partner, hidden: true}

  # Pages
  - name: pages
    label: "Pages"
    editor:
      preview: false  
    files:

      # Home
      - file: data/pages/start.yml
        name: start
        label: "Home"
        fields: 
          - { name: slug, default: "", widget: hidden }
          - { name: video, label: Video, widget: file }
          - name: news
            label: News
            widget: object
            fields:
            - { name: heading, label: "Heading", widget: string, default: "Latest News" }
            - { name: link, label: "Text on link to news page", widget: string, default: "Show all" }     
            - { name: noNews, label: "Text to show when there's no news", widget: string, default: "There are no news yet!" }     
          - name: live
            label: Live
            widget: object
            fields:
            - { name: heading, label: "Heading", widget: string, default: "Latest Gigs" }
            - { name: link, label: "Text on link to gigs page", widget: string, default: "Show all" }
            - { name: noGigs, label: "Text to show when there's no upcoming gigs", widget: string, default: "There are no upcoming gigs!" }     
      
      # News Page
      - file: data/pages/news.yml
        name: news
        label: "News"
        fields:
          - { name: slug, default: news, widget: hidden }
          - { name: title, label: Title, widget: string }
          - { name: noNews, label: "Text to show when there's no news", widget: string, default: "There are no news yet!" }
      
      # Music Page
      - file: data/pages/music.yml
        name: music
        label: "Music"
        fields:
          - { name: slug, default: music, widget: hidden }
          - { name: title, label: Title, widget: string }
          - { name: discoHeading, label: "Discography Heading", widget: string }
          - name: discography
            label: "Discography"
            summary: "{{title}}"
            widget: list
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "Release Date", name: date, widget: datetime }
              - { label: "Cover Image", name: image, widget: image, required: false }
              - { label: "Information", name: info, widget: text }
              - name: tracks
                label: "Tracks"
                summary: "{{track}}"
                widget: list
                fields:
                  - { label: "Track", name: track, widget: string }
                  - { label: ID, name: id, widget: ncw-id, prefix: track, hidden: true}
              - name: links
                label: "Links"
                summary: "{{title}}"
                widget: list
                fields:
                  - { label: "Title", name: title, widget: string }
                  - { label: "Link", name: link, widget: string }
                  - { label: ID, name: id, widget: ncw-id, prefix: link, hidden: true }
              - { label: ID, name: id, widget: ncw-id, prefix: disco, hidden: true }
          - { name: videoHeading, label: "Videos Heading", widget: string }
          - name: videos
            label: "Music Videos"
            summary: "{{title}}"
            widget: list
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "YouTube Video ID", name: videoId, widget: string }
              - { label: ID, name: id, widget: ncw-id, prefix: video, hidden: true }
      
      # Live Page
      - file: data/pages/live.yml
        name: live
        label: "Live"
        fields:
          - { name: slug, default: live, widget: hidden }
          - { name: title, label: Title, widget: string }
          - { name: upcomingHeading, label: "Heading for upcoming gigs", widget: string, default: "Upcoming dates" }
          - { name: noUpcoming, label: "Text to show when there's no upcoming gigs", widget: string, default: "There are no upcoming gigs!" }     
          - { name: pastHeading, label: "Heading for past gigs", widget: string, default: "Past dates" }
          - { name: noPast, label: "Text to show when there's no past gigs", widget: string, default: "There are no past gigs!" }     
          - name: gigs
            label: "Gigs"
            summary: "{{location}}: {{venue}} - {{date}}"
            widget: list
            fields:
              - { label: Date, name: date, widget: datetime }
              - { label: "City / Country", name: location, widget: string }
              - { label: Venue, name: venue, widget: string }
              - { label: "Tickets Link", name: link, widget: string, required: false }
              - { label: ID, name: id, widget: ncw-id, prefix: gig, hidden: true }

      # Contact Page
      - file: data/pages/contact.yml
        name: contact
        label: "Contact"
        fields:
          - { name: slug, default: contact, widget: hidden }
          - { name: title, label: Title, widget: string }
          - { name: nameLabel, label: "Name label", widget: string }
          - { name: eMailLabel, label: "Email label", widget: string }
          - { name: subjectLabel, label: "Subject label", widget: string }
          - { name: messageLabel, label: "Message label", widget: string }
          - { name: submitLabel, label: "Submit label", widget: string }
          - { name: nameErrorMsg, label: "Name error message", widget: string }
          - { name: eMailErrorMsg, label: "Email error message", widget: string }
          - { name: subjectErrorMsg, label: "Subject error message", widget: string }
          - { name: messageErrorMsg, label: "Message error message", widget: string }
          - { name: success, label: "Confirmation message", widget: text }
          - { name: nameRegexp, label: "Name validation regexp", widget: string }
          - { name: eMailRegexp, label: "E-mail validation regexp", widget: string }
          - { name: subjectRegexp, label: "Subject validation regexp", widget: string }
          - { name: messageRegexp, label: "Message validation regexp", widget: string }

  # Custom Pages
  - folder: data/custom-pages
    name: "customPages"
    label: "Custom Pages"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: logo, label: Custom Logo, widget: image, required: false, description: "Optional custom logotype to display in header." }
      - { name: image, label: "Featured image", widget: image, required: false }
      - name: body
        label: "Content"
        widget: markdown
        buttons: [bold, italic, link, heading-three, heading-four, heading-five, heading-six, quote, bulleted-list, numbered-list]
        editor_components: [image]
      - { name: type, default: custom-page, widget: hidden }

  # News
  - folder: data/news
    name: "news"
    label: News
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{hour}}{{minute}}{{second}}-{{slug}}"
    summary: "{{title}} - {{date}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: "Publish date", widget: datetime }
      - { name: image, label: "Featured image", widget: image, required: false }
      - name: body
        label: "Content"
        widget: markdown
        buttons: [bold, italic, link, heading-three, heading-four, heading-five, heading-six, quote, bulleted-list, numbered-list]
        editor_components: [image]
      - { name: type, default: news, widget: hidden }
